from django.conf.urls.defaults import *
from forums.views import PostSearchView

urlpatterns = patterns('forums.views',
	(r'^$', 'index'),
	(r'^(?P<forum_id>\d+)/$', 'forum_view'),
	(r'^(?P<forum_id>\d+)/action/$', 'forum_action'),
	(r'^(?P<forum_id>\d+)/action/merge/$', 'topics_merge'),
	(r'^topic/(?P<topic_id>\d+)/$', 'topic_view'),
	(r'^topic/(?P<topic_id>\d+)/(?P<page>\d+)/$', 'topic_view'),
	(r'^topic/new/(?P<forum_id>\d+)/$', 'topic_new'),
	(r'^topic/reply/(?P<topic_id>\d+)/$', 'post_new'),
	(r'^topic/reply/(?P<topic_id>\d+)/q/(?P<quoted_post_id>\d+)$', 'post_new'),
	(r'^topic/delete/(?P<topic_id>\d+)/$', 'topic_delete'),
	(r'^topic/action/(?P<topic_id>\d+)/$', 'topic_action'),
	(r'^topic/close/(?P<topic_id>\d+)/$', 'topic_close'),
	(r'^topic/open/(?P<topic_id>\d+)/$', 'topic_open'),
	(r'^topic/stick/(?P<topic_id>\d+)/$', 'topic_stick'),
	(r'^topic/unstick/(?P<topic_id>\d+)/$', 'topic_unstick'),
	(r'^topic/move/(?P<topic_id>\d+)/$', 'topic_move'),
	(r'^topic/delete/posts/(?P<topic_id>\d+)/$', 'posts_delete'),
	(r'^topic/split/posts/(?P<topic_id>\d+)/$', 'posts_split'),
	(r'^post/(?P<post_id>\d+)/', 'post_permalink'),
	(r'^post/edit/(?P<post_id>\d+)/$', 'post_edit'),
	(r'^post/delete/(?P<post_id>\d+)/$', 'post_delete'),
	(r'^post/report/(?P<post_id>\d+)/', 'post_report'),
	(r'^post/vote/up/(?P<post_id>\d+)/$', 'post_voteup'),
	(r'^post/vote/cancel/(?P<post_id>\d+)/$', 'post_votecancel'),
	(r'^post/vote/down/(?P<post_id>\d+)/$', 'post_votedown'),
	(r'^mark_as_read/$', 'mark_as_read'),
	url(r'^search/$', PostSearchView(), name='forum_search'),
	(r'^search/latest/$', 'search_latest'),
	(r'^search/unread/$', 'search_unread'),
)
